from django.db import models

LANGUAGES_CHOICES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('zh', 'Chinese'),
    ('ja', 'Japanese'),
    ('ru', 'Russian'),
    ('pt', 'Portuguese'),
    ('hi', 'Hindi'),
    ('ar', 'Arabic'),
    ('it', 'Italian'),
    ('ko', 'Korean'),
    ('tr', 'Turkish'),
    ('nl', 'Dutch'),
    ('pl', 'Polish'),
]

class GenderChoices(models.TextChoices):
        MALE = 'M', 'Male'
        FEMALE = 'F', 'Female'


from django.db import models

class NationalityChoices(models.TextChoices):
    AFGHAN = 'afghan', 'Afghan'
    ALBANIAN = 'albanian', 'Albanian'
    ALGERIAN = 'algerian', 'Algerian'
    AMERICAN = 'american', 'American'
    ANDORRAN = 'andorran', 'Andorran'
    ANGOLAN = 'angolan', 'Angolan'
    ANTIGUAN = 'antiguan', 'Antiguan'
    ARGENTINE = 'argentine', 'Argentine'
    ARMENIAN = 'armenian', 'Armenian'
    AUSTRALIAN = 'australian', 'Australian'
    AUSTRIAN = 'austrian', 'Austrian'
    AZERBAIJANI = 'azerbaijani', 'Azerbaijani'
    BAHAMIAN = 'bahamian', 'Bahamian'
    BAHRAINI = 'bahraini', 'Bahraini'
    BANGLADESHI = 'bangladeshi', 'Bangladeshi'
    BARBADIAN = 'barbadian', 'Barbadian'
    BELARUSIAN = 'belarusian', 'Belarusian'
    BELGIAN = 'belgian', 'Belgian'
    BELIZEAN = 'belizean', 'Belizean'
    BENINESE = 'beninese', 'Beninese'
    BHUTANESE = 'bhutanese', 'Bhutanese'
    BOLIVIAN = 'bolivian', 'Bolivian'
    BOSNIAN = 'bosnian', 'Bosnian'
    BOTSWANAN = 'botswanan', 'Botswanan'
    BRAZILIAN = 'brazilian', 'Brazilian'
    BRITISH = 'british', 'British'
    BRUNEIAN = 'bruneian', 'Bruneian'
    BULGARIAN = 'bulgarian', 'Bulgarian'
    BURKINABE = 'burkinabe', 'Burkinabe'
    BURMESE = 'burmese', 'Burmese'
    BURUNDIAN = 'burundian', 'Burundian'
    CAMBODIAN = 'cambodian', 'Cambodian'
    CAMEROONIAN = 'cameroonian', 'Cameroonian'
    CANADIAN = 'canadian', 'Canadian'
    CAPE_VERDEAN = 'cape_verdean', 'Cape Verdean'
    CENTRAL_AFRICAN = 'central_african', 'Central African'
    CHADIAN = 'chadian', 'Chadian'
    CHILEAN = 'chilean', 'Chilean'
    CHINESE = 'chinese', 'Chinese'
    COLOMBIAN = 'colombian', 'Colombian'
    COMORAN = 'comoran', 'Comoran'
    CONGOLESE = 'congolese', 'Congolese'
    COSTA_RICAN = 'costa_rican', 'Costa Rican'
    CROATIAN = 'croatian', 'Croatian'
    CUBAN = 'cuban', 'Cuban'
    CYPRIOT = 'cypriot', 'Cypriot'
    CZECH = 'czech', 'Czech'
    DANISH = 'danish', 'Danish'
    DJIBOUTIAN = 'djiboutian', 'Djiboutian'
    DOMINICAN = 'dominican', 'Dominican'
    DUTCH = 'dutch', 'Dutch'
    EAST_TIMORESE = 'east_timorese', 'East Timorese'
    ECUADOREAN = 'ecuadorean', 'Ecuadorean'
    EGYPTIAN = 'egyptian', 'Egyptian'
    EMIRATI = 'emirati', 'Emirati'
    EQUATORIAL_GUINEAN = 'equatorial_guinean', 'Equatorial Guinean'
    ERITREAN = 'eritrean', 'Eritrean'
    ESTONIAN = 'estonian', 'Estonian'
    ETHIOPIAN = 'ethiopian', 'Ethiopian'
    FIJIAN = 'fijian', 'Fijian'
    FINNISH = 'finnish', 'Finnish'
    FRENCH = 'french', 'French'
    GABONESE = 'gabonese', 'Gabonese'
    GAMBIAN = 'gambian', 'Gambian'
    GEORGIAN = 'georgian', 'Georgian'
    GERMAN = 'german', 'German'
    GHANAIAN = 'ghanaian', 'Ghanaian'
    GREEK = 'greek', 'Greek'
    GRENADIAN = 'grenadian', 'Grenadian'
    GUATEMALAN = 'guatemalan', 'Guatemalan'
    GUINEAN = 'guinean', 'Guinean'
    GUYANESE = 'guyanese', 'Guyanese'
    HAITIAN = 'haitian', 'Haitian'
    HONDURAN = 'honduran', 'Honduran'
    HUNGARIAN = 'hungarian', 'Hungarian'
    ICELANDIC = 'icelandic', 'Icelandic'
    INDIAN = 'indian', 'Indian'
    INDONESIAN = 'indonesian', 'Indonesian'
    IRANIAN = 'iranian', 'Iranian'
    IRAQI = 'iraqi', 'Iraqi'
    IRISH = 'irish', 'Irish'
    ISRAELI = 'israeli', 'Israeli'
    ITALIAN = 'italian', 'Italian'
    IVOIRIAN = 'ivoirian', 'Ivoirian'
    JAMAICAN = 'jamaican', 'Jamaican'
    JAPANESE = 'japanese', 'Japanese'
    JORDANIAN = 'jordanian', 'Jordanian'
    KAZAKH = 'kazakh', 'Kazakh'
    KENYAN = 'kenyan', 'Kenyan'
    KOREAN = 'korean', 'Korean'
    KUWAITI = 'kuwaiti', 'Kuwaiti'
    KYRGYZ = 'kyrgyz', 'Kyrgyz'
    LAO = 'lao', 'Lao'
    LATVIAN = 'latvian', 'Latvian'
    LEBANESE = 'lebanese', 'Lebanese'
    LIBERIAN = 'liberian', 'Liberian'
    LIBYAN = 'libyan', 'Libyan'
    LITHUANIAN = 'lithuanian', 'Lithuanian'
    LUXEMBOURGISH = 'luxembourgish', 'Luxembourgish'
    MACEDONIAN = 'macedonian', 'Macedonian'
    MALAGASY = 'malagasy', 'Malagasy'
    MALAWIAN = 'malawian', 'Malawian'
    MALAYSIAN = 'malaysian', 'Malaysian'
    MALIAN = 'malian', 'Malian'
    MALTESE = 'maltese', 'Maltese'
    MAURITANIAN = 'mauritanian', 'Mauritanian'
    MAURITIAN = 'mauritian', 'Mauritian'
    MEXICAN = 'mexican', 'Mexican'
    MOLDOVAN = 'moldovan', 'Moldovan'
    MONACAN = 'monacan', 'Monacan'
    MONGOLIAN = 'mongolian', 'Mongolian'
    MONTENEGRIN = 'montenegrin', 'Montenegrin'
    MOROCCAN = 'moroccan', 'Moroccan'
    MOZAMBICAN = 'mozambican', 'Mozambican'
    NAMIBIAN = 'namibian', 'Namibian'
    NEPALESE = 'nepalese', 'Nepalese'
    NEW_ZEALANDER = 'new_zealander', 'New Zealander'
    NICARAGUAN = 'nicaraguan', 'Nicaraguan'
    NIGERIAN = 'nigerian', 'Nigerian'
    NORWEGIAN = 'norwegian', 'Norwegian'
    OMANI = 'omani', 'Omani'
    PAKISTANI = 'pakistani', 'Pakistani'
    PANAMANIAN = 'panamanian', 'Panamanian'
    PARAGUAYAN = 'paraguayan', 'Paraguayan'
    PERUVIAN = 'peruvian', 'Peruvian'
    PHILIPPINE = 'philippine', 'Philippine'
    POLISH = 'polish', 'Polish'
    PORTUGUESE = 'portuguese', 'Portuguese'
    QATARI = 'qatari', 'Qatari'
    ROMANIAN = 'romanian', 'Romanian'
    RUSSIAN = 'russian', 'Russian'
    RWANDAN = 'rwandan', 'Rwandan'
    SAUDI = 'saudi', 'Saudi'
    SCOTTISH = 'scottish', 'Scottish'
    SENEGALESE = 'senegalese', 'Senegalese'
    SERBIAN = 'serbian', 'Serbian'
    SINGAPOREAN = 'singaporean', 'Singaporean'
    SLOVAK = 'slovak', 'Slovak'
    SLOVENIAN = 'slovenian', 'Slovenian'
    SOMALI = 'somali', 'Somali'
    SOUTH_AFRICAN = 'south_african', 'South African'
    SPANISH = 'spanish', 'Spanish'
    SRI_LANKAN = 'sri_lankan', 'Sri Lankan'
    SUDANESE = 'sudanese', 'Sudanese'
    SURINAMESE = 'surinamese', 'Surinamese'
    SWAZI = 'swazi', 'Swazi'
    SWEDISH = 'swedish', 'Swedish'
    SWISS = 'swiss', 'Swiss'
    SYRIAN = 'syrian', 'Syrian'
    TAIWANESE = 'taiwanese', 'Taiwanese'
    TAJIK = 'tajik', 'Tajik'
    TANZANIAN = 'tanzanian', 'Tanzanian'
    THAI = 'thai', 'Thai'
    TOGOLESE = 'togolese', 'Togolese'
    TRINIDADIAN = 'trinidadian', 'Trinidadian'
    TUNISIAN = 'tunisian', 'Tunisian'
    TURKISH = 'turkish', 'Turkish'
    TURKMEN = 'turkmen', 'Turkmen'
    UGANDAN = 'ugandan', 'Ugandan'
    UKRAINIAN = 'ukrainian', 'Ukrainian'
    URUGUAYAN = 'uruguayan', 'Uruguayan'
    UZBEK = 'uzbek', 'Uzbek'
    VENEZUELAN = 'venezuelan', 'Venezuelan'
    VIETNAMESE = 'vietnamese', 'Vietnamese'
    WELSH = 'welsh', 'Welsh'
    YEMENI = 'yemeni', 'Yemeni'
    ZAMBIAN = 'zambian', 'Zambian'
    ZIMBABWEAN = 'zimbabwean', 'Zimbabwean'
