services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    
volumes:
  db_data: